sudo: required

services:
  - docker

language: python
python:
  - '3.6'
install: pip install pytest
cache: pip
matrix:
  fast_finish: true

before_script:
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin

env:
  global:
  - secure: kzwJoESooX561LMeh7fjW4noP4JpFAGMvf5sAQAZ0IOzuHjpEAHytT1eARNnoLMy/+NvvKQswimYPtB59caPWdcZCkjh0tBlCzOvuA0vfrA+otYqOZR4hg7LdFELClVFUA7e5++AysBhhWJmNRjvCtkrxtLz/puJIMWAfKSASUNtwVeK/o47EIhjxdrxNUO3rNoIMbPpbFNAD8WOROfvVuRdxXkuF/ugilg0Cm/staA9ADoNYFmOw5ZCsHJQNngMMIx84rbGR6rUzxEgK9aYnesNuv2Qcz8VmbaDoOf24avDpwEFXBgzDZJGD5jIuJuQ4FDXhm+7VHBUsEhl5CAE9QD9MhjoO3uwcs4YmoTK0L9kCgyvITZk7bNI/VHR2gwRQdWTX6QpOv83HX4sUMoU3aA11W1b4LfTHj/3xVEm754G1o911bFcfwCGiOpeOzApp1T3YHwLN1oYIa8m3WZy58bv+7xZ7R4xzN3KSzKMO2MsNjVoVeIyKLIp6++J6IaPLmMRzqF/ZngDbip+ASDHwq7CGfjmslAPdRvEZg5DyLQf/d+6BdcuCiwNUA/0GI/Ax6bKTgD1m8HMOUbaiLNO4g+gEb+ta9hOktru/YIZHr+akRRLhPyAhNm17c8X9vwCLknVR/IVpb66Zrf7JCojF0kuNtygBNVy/JILSpm5L0g=
  - secure: t5aaF70NR5XDvz/CBe/Gw82J1xaPMNbzIbzlg7ImzQP/DCZYnOXtRKtLby4iJHh//0IrSMj/ECksJqXEc5nKLYfeB40DVH3h7wzHlDlz6dkb3X2KMbmVuhwSch4VxEvsitCf1t3cP3wQrjxLw3XYCyzeiD3/mdcOQj6H8TZRqn1+XL8GDV+ZTruMJi2qO8Oy/I/STpKhKUeA/ank+5MEyemDm+AcyOEGfay2tMsCqUw+IaZnTSdsZ+9r3vF0g/2UtD9IIsuLjlbZs5iDf2XmebxpIp34p8672Nhs92HkbMBeIJOEe5J9z+kujBbAXUhvokAiaqPWzTHolWMYLH5/wUSAVEnpnCXvnCQkQ+et1Q7Kks4XfREdwx4/zvV7ckMNRBZzdV9A/uDL+y5FARHrfRyf8qEq5XBBjvYJAuYEKiYPbJgkHvxEfALhLQs5iRHovJLn3fWgvHrzAdSjdlbv3S2oahOdUDcNqqCSrJ9FOgElzETFasDvHeX7lmvqTeQv5tSxirVDeVs0jj8LIOjvKnfd4pCSCrReYzq0Yw66qBkP0GYn/fG0iTnRJEZWaONZ+M+DPtztngjmu+G+WBF1vkQHtfYGrvyEQsGD10WAxdtgHhpMmktwjs/Nqk62r341KZhxJ3Sn0T/th9zDDQkSaPJvnztuTrnGiSHWbyyRS+4=

script:
  - "./build.sh"
  - docker run --rm -d -p "8000:8000" sbneto/tesseract4:python-por-rpc
  - sleep 10
  - docker ps
  - pytest
  - "./push.sh"
